### ISSUE TITLE
Placing accents over characters has unexpected behaviour in Safari

### ISSUE THREAD

**Issue by evasteingrims** [ianstormtaylor/slate#3139]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?
_Safari_

When placing accents over characters the caret moves to a weird place. This can be reproduces in this example: https://www.slatejs.org/examples/rich-text.

![caret-jump-safari](https://user-images.githubusercontent.com/11168195/69808017-96490080-11de-11ea-8b82-4a79d481b429.gif)

Slate version: 0.50.0
Safari version: 12.0.1 (14606.2.104.1.1)
MacOs 10.14.1 (18B75)

#### What's the expected behavior?

The caret should not jump backward or be duplicated when placing accents over characters

**Comment by ianstormtaylor** [comment]
The Firefox one is a larger issue, tracking it in https://github.com/ianstormtaylor/slate/issues/3141.

For the Safari one I'm less sure, but anyone who can investigate why the selection isn't right would be awesome!

**Comment by palodelincak** [comment]
It looks like this issue is still pending?

I just finished migration from Draft to Slate in our app and in the end of migration I discover that accents are buggy in Safari? Damn, such a dealbreaker.

**Comment by ximomompo** [comment]
Hi, we are looking to solve this issue. Anyone has a trick or something to resolve it?

**Comment by pzhine** [comment]
This is fixed now, as of slate-react@0.62.1. Here's the relevant diff patch: https://github.com/ianstormtaylor/slate/compare/v0.61.3...slate-react@0.62.1#diff-1d0c52ec4c5562d96965f789988bd4efd4a6d24b88527918987d06bcc43d15adR377

**Comment by musemind** [comment]
@pzhine what exactly is the fix for this issue? We still have this problem after an "async" decoration update.
We are on slate `^0.63.0` and slate-react `0.65.2`, so this patch should be already included.

https://user-images.githubusercontent.com/11320794/139849715-841b1f9c-3459-49b8-8f40-f4ead0750df2.mov

**Comment by volnei** [comment]
Please, reopen this issue... still with errors

**Comment by cguellner** [comment]
what exactly is fixing this issue?
