### ISSUE TITLE
[ Backspace + Space ] Leads to Repetition and continous [ Backspace ] leads to crash of Slate js Example on android device.

### ISSUE THREAD

**Issue by RavenColEvol** [ianstormtaylor/slate#3811]
####  Backspace + Space ] Leads to Repetition and continous [ Backspace ] leads to crash of Slate js Example on android device.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44892121/89117622-fa823980-d4bc-11ea-8ccf-32325ef7b3cf.gif)

Slate: 0.58.X
Browser: Chrome
OS: Android

**Comment by thesunny** [comment]
@RavenColEvol 

Slate currently doesn't support Android devices.

There is a KickStarter to add support for it though

[Kickstarter for Android Support](https://github.com/ianstormtaylor/slate/issues/3786)

**Comment by badrequest400** [comment]
So we've sunk a lot of time into making Slate work for us. It is a good idea and generally a good editor, thanks for the work!

However I feel like the documentation should SCREAM about this... After a tonne of man hours on this, we now need to rip it out and go with something else.

**Comment by duongmngo** [comment]
I got the same issue on 
- Mac OS. (Still working well on Window).
- Chrome
- Unicode. (Still working well with English).

**Comment by duongmngo** [comment]
Reproduce: 
Step 1:  Type Unicode sentence. 
Step 2:  Backspace until empty, then type 1 character. The placeholder is not hidden while the text is showing.

**Comment by duongmngo** [comment]
`placeholder={!focusTextBox ? placeholder || t('enter-your-text') : undefined}`
Fixed!!

**Comment by idonov** [comment]
This is still reproducible with 0.63 on android.
Random crashes on space, backspace or enter.
Both Unicode and NonUnicode
Text seems its duplicating randomly.

I really hope this will get fixed, for now I have to scrape the editor on android
