### ISSUE TITLE
IME bug on Firefox

### ISSUE THREAD

**Issue by sennpang** [ianstormtaylor/slate#3824]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
1.press Enter key, create new blank line
2.input some characters
3.delete characters, make focus on start of the line
4.input Chinese
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16861647/90204596-f89d6c00-de14-11ea-8b88-fb8516849977.gif)

**but if i change the focus, it's correct when i input Chinese**
**after step 3, i move the focus to previous line and then comeback**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16861647/90207501-0228d300-de19-11ea-8969-fae2cf78da48.gif)

Slate: latest
Browser:  Firefox
OS: Mac  / Windows

**Comment by scil** [comment]
it's about IME bug.  Chinsese can not be used well on slate right now. because IME related DOM event damage React  Reconciliation.

**Comment by baijiahei** [comment]
but this bug only happens on Firefox

**Comment by laobeijing0806** [comment]
there is a pr would fix this bug. [#3768](https://github.com/ianstormtaylor/slate/pull/3768)

**Comment by laobeijing0806** [comment]
Just met this problem, if you delete characters to an empty line and input Chinese, in Firefox it will cause composition characters left in the Dom tree, like these 
![image](https://user-images.githubusercontent.com/17963602/99648773-60a3c400-2a8e-11eb-9756-fd77019a3ca8.png)

I tried some ways to debug, and found out that if DomSelection place on the `data-slate-leaf` node, and it would replace this bug. Anyone got an idea? Not sure if it's a Firefox bug, or something else reason that cause this.

**Comment by maxam2017** [comment]
Are there any updates? i still encounter this issue on Firebox 🤯 
 
slate version: v0.60.2

**Comment by 1c7** [comment]
So how to fix this problem?

**Comment by NearImba** [comment]
I found this had been fixed in v0.63
Could somebody provide the simplest solution to fixed this in v0.59 please ?

**Comment by xxxxxccc** [comment]
same error; version 0.70.0, 2011.11.11;

**Comment by samkk** [comment]
"slate": "^0.72.3",
    "slate-history": "^0.66.0",
    "slate-react": "^0.72.1",

There is the same problem, still not fixed, Chinese directly exploded in Firefox
Is there a solution?
