### ISSUE TITLE
ctrl + a > 中文输入法下输入，编辑器会卡住

### ISSUE THREAD

**Issue by LazyJoke** [ianstormtaylor/slate#4316]

**Comment by liangxiwei** [comment]
why are you speek chinese,who understand what you say?

**Comment by 7sharp9** [comment]
According to Google Translate:
>Input under Chinese input method, the editor will be stuck.

Im not sure if the OP is referring to issue with alt character input.  There is a case where the placeholder text is not cancelled if you enter ```ALT + ` ``` for example the placeholder is not cancelled:

![Screenshot 2021-06-25 at 18 39 31](https://user-images.githubusercontent.com/588746/123464432-b15f3a80-d5e4-11eb-988c-a714fb5c018a.png)

Screen shot via:  https://www.slatejs.org/examples/plaintext

I can log this as a separate issue though if wanted?

**Comment by liangxiwei** [comment]
> According to Google Translate:
> 
> > Input under Chinese input method, the editor will be stuck.
> 
> Im not sure if the OP is referring to issue with alt character input. There is a case where the placeholder text is not cancelled if you enter `` ALT + ` `` for example the placeholder is not cancelled:
> 
> ![Screenshot 2021-06-25 at 18 39 31](https://user-images.githubusercontent.com/588746/123464432-b15f3a80-d5e4-11eb-988c-a714fb5c018a.png)
> 
> Screen shot via: https://www.slatejs.org/examples/plaintext
> 
> I can log this as a separate issue though if wanted?

this issue was fixed,but the example demo source code is too old.

**Comment by samkk** [comment]
"slate": "^0.72.3",
"slate-history": "^0.66.0",
"slate-react": "^0.72.1",

There is the same problem, still not fixed, Chinese directly exploded in Firefox
Is there a solution?
