### ISSUE TITLE
Editors don't support dynamic placeholders?

### ISSUE THREAD

**Issue by anewusr** [ianstormtaylor/slate#601]
Hey,

I've noticed that placeholders for Slate's Editor won't change after being passed in the first time.
So if the initial placeholder value was "Write here", passing in new props with a new placeholder "Write here again" will not change the display. The empty Editor state will continue to show the first placeholder "Write here".

Is this expected behavior?

My current & inefficient workaround is to discard and rebuild the Editor component whenever the placeholder value changes.

My Slate version is @ 0.16.8, my React version is @ 15.3.2, and my Node version is @ v6.9.5

Any advice would be most appreciated! I

Examples:
<code>
                <Editor
                    schema={schema}
                    state={this.state.state}
                    onKeyDown={this.onKeyDown}
                    onChange={this.onChange}
                    onDocumentChange={this.onDocumentChange || (() => {})}
                    placeholder={<div className="translucent">
                        {this.props.placeholder || <span>Your text or description <span className="fa fa-pencil"/></span>}
                    </div>}
                />
</code>

Or even more simply:
<code>
                <Editor
                    schema={schema}
                    state={this.state.state}
                    placeholder={this.props.placeholder}
                />
</code>

**Comment by ianstormtaylor** [comment]
Hey @anewusr thanks for reporting this! I've just pushed up a change that I think should fix it, and am releasing a new patch version now. Let me know if not!

**Comment by lxcid** [comment]
I didn't work for me though.

I believe its because the placeholder props are passed in during the [initialisation of core `Plugin`](https://github.com/ianstormtaylor/slate/blob/ad2642a3b5ac489615a4301e65d3ac0c6618031d/src/plugins/core.js#L30) instead of participating in component updates but I am not yet good to verify my hypothesis.

**Comment by anewusr** [comment]
@ianstormtaylor 

I appreciate your super fast commit, but in v0.16.17,  the placeholders are still not updating when the props change.

I think lxcid might be onto something.

**Comment by ianstormtaylor** [comment]
I think this is fixed, since the placeholder API was revamped.

**Comment by valorize** [comment]
I can't confirm that it works. Is there a general codepen with a working editor? So I could create a testcase?

**Comment by exeto** [comment]
It doesn't work
https://codesandbox.io/embed/slate-placeholder-update-fzfwc

**Comment by valoricDe** [comment]
@ianstormtaylor let's reopen this ticket, as we have been proven wrong 😅

**Comment by mmdonaldson** [comment]
Also experiencing this, any workarounds?

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
