### ISSUE TITLE
triple-click to select block, selection extends to next block

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#752]
http://slatejs.org/#/rich-text?
Triple click to select the first paragraph. Click header 1 button. Note that the second paragraph became H1 as well.

**Comment by ianstormtaylor** [comment]
Hey @AlexeiAndreev thanks for reporting this.

I agree it's something that should be fixed. It looks like [Draft handles this](https://github.com/facebook/draft-js/blob/213cd764f61cc64552bddd672ae1748529d55333/src/model/modifier/RichTextEditorUtil.js#L262-L265) by fixing these types of selections before using `setBlock`. If anyone is interested in helping, I'd be open to a pull request that does similar!

**Comment by ianstormtaylor** [comment]
See https://github.com/ianstormtaylor/slate/pull/863#issuecomment-307659171

**Comment by pauliusef** [comment]
Could we re-open this issue, as it's still happening with applying list styles (ordered, unordered) in the same rich text editor example.

http://slatejs.org/#/rich-text
Triple click to select the first paragraph. Click ordered/unordered list button. See, that the previous block gets added inside the list element.

**Comment by prichodko** [comment]
@ianstormtaylor I can work on this if @ianstormtaylor could point in the right direction.

**Comment by jaredtmartin** [comment]
Like prichodko suggests, this is still an issue.  When you triple-click, the selection in slate is only on the word, not the whole leaf.  My theory is that if you then edit, slate's state gets out o sync with reality causing it to crash. I'm gonna see if I can find a way to patch this.

**Comment by rohankeskar19** [comment]
Is there a fix for this now?

**Comment by smnbbrv** [comment]
For the affected ones, here is quick-and-dirty solution.

On every selection change, run the following:

```
const selection = this.editor.selection;

if (selection && selection.anchor.path[0] === selection.focus.path[0] - 1 && selection.focus.path[1] === 0) {
  Transforms.move(this.editor, { distance: 1, unit: 'character', edge: 'focus', reverse: true });
}
```

This actually checks if the end of the selection lands on a start of a new line while the selection itself originates at the previous line and moves the cursor 1 symbol back.

Of course I would appreciate a real fix for this instead

**Comment by norahsana** [comment]
For the affected ones, the above solution did not work for me but this did:

```
const { anchor, focus } = editor.selection

  if (
    anchor.path[1] !== undefined &&
    focus.path[1] !== undefined &&
    anchor.path[1] < focus.path[1] &&
    focus.path[2] === 0 &&
    focus.offset === 0
  ) {
    Transforms.move(editor, { distance: 1, unit: 'character', edge: 'focus', reverse: true })
  }
```
