### ISSUE TITLE
[IME] FF/macOS: entering accented letters from the Accent Menu inserts double character

### ISSUE THREAD

**Issue by danburzo** [ianstormtaylor/slate#982]
#### Do you want to request a *feature* or report a *bug*?

There is a __bug__ in Firefox/macOS with entering an accented letter from the [Accent Menu](https://support.apple.com/kb/PH25643?locale=en_US) (by holding down a key and pressing the keys _1_ to _N_). 

#### What's the current behavior?

At the subsequent key press (e.g. moving the caret with left/right arrow key), the non-accented character appears along with the accented one. [See video here](https://www.dropbox.com/s/fwpsfwuuqi1lbgw/accent-menu.mov?dl=0)

#### What's the expected behavior?

A single, accented letter is inserted. Safari/Chrome work as expected.

#### Other RTEs

* _Draft.js_ exhibits the same problem
* _ProseMirror_ and _Quill_ don't seem to have it

**Comment by danburzo** [comment]
Seems the Accent Menu does not fire `compositionstart` / `compositionend` events on Chrome & Safari, and Firefox fires both `compositionstart` and `compositionend` after the character has been composed.

There's also an [open, albeit deserted, issue](https://github.com/w3c/editing/issues/132) raised for the W3C Editing WG.

**Comment by danburzo** [comment]
This works as expected with `isNative = false` but that does not make any sense to me, since when entering the character `à`, there are two `beforeinput`/`input` events, one with `a` and one with `à` 🤔

**Comment by ianstormtaylor** [comment]
I believe this is fixed in the latest version of Slate.

**Comment by javierfernandes** [comment]
This is still happening for me in `"slate": "^0.44.12",`
But I'm also able to reproduce this in the current demo editor from https://www.slatejs.org/#/rich-text
![slate-accent-menu-bug](https://user-images.githubusercontent.com/4428120/63605831-1c80f580-c5a5-11e9-8e23-18369dc9037b.gif)

Should this be reopened @ianstormtaylor  ?

Thanks

**Comment by knubie** [comment]
This occurs in Chrome as well.

**Comment by achou11** [comment]
There's a PR for this that's looks ready to be merged: https://github.com/ianstormtaylor/slate/pull/3041

Will probably require a slate upgrade

**Comment by jens-lilt** [comment]
I can still see this occur in Slate 0.77.2 if I use the arrow keys to select the accent instead of typing the number shown underneath
